import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Link } from "wouter";
import { Users, DollarSign, TrendingUp, Bot, Plus, Trash2, ArrowLeft } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { apiRequest } from "@/lib/queryClient";
import { GlassCard, GoldButton, GhostButton, GoldHeading, SfsContainer } from "@/components/sfs";

interface Client {
  id: number;
  businessName: string;
  contactEmail: string | null;
  contactPhone: string | null;
  monthlyFee: string;
  status: string;
  createdAt: Date;
  botCount?: number;
  totalRevenue?: number;
}

export default function ClientsPage() {
  const queryClient = useQueryClient();
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [formData, setFormData] = useState({
    businessName: "",
    contactEmail: "",
    contactPhone: "",
    monthlyFee: "",
  });

  const { data: clients = [], isLoading } = useQuery<Client[]>({
    queryKey: ["/api/clients"],
  });

  const createClientMutation = useMutation({
    mutationFn: async (clientData: typeof formData) => {
      return await apiRequest("POST", "/api/clients", clientData);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/clients"] });
      setIsAddDialogOpen(false);
      setFormData({ businessName: "", contactEmail: "", contactPhone: "", monthlyFee: "" });
    },
  });

  const deleteClientMutation = useMutation({
    mutationFn: async (clientId: number) => {
      return await apiRequest("DELETE", `/api/clients/${clientId}`, undefined);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/clients"] });
    },
  });

  const totalClients = clients.length;
  const totalMonthlyRevenue = clients.reduce((sum, c) => sum + parseFloat(c.monthlyFee || "0"), 0);
  const totalBotRevenue = clients.reduce((sum, c) => sum + (c.totalRevenue || 0), 0);
  const totalActiveBots = clients.reduce((sum, c) => sum + (c.botCount || 0), 0);

  const handleAddClient = () => createClientMutation.mutate(formData);
  const handleDeleteClient = (clientId: number) => {
    if (confirm("Are you sure you want to delete this client? This will also delete all their bots.")) {
      deleteClientMutation.mutate(clientId);
    }
  };

  const stats = [
    { label: "Total Clients", value: totalClients, Icon: Users, sub: undefined as string | undefined },
    { label: "Monthly Revenue", value: `£${totalMonthlyRevenue.toFixed(2)}`, Icon: DollarSign, sub: "From client fees" },
    { label: "Bot Revenue", value: `£${totalBotRevenue.toFixed(2)}`, Icon: TrendingUp, sub: "Generated by bots" },
    { label: "Active Bots", value: totalActiveBots, Icon: Bot, sub: undefined },
  ];

  return (
    <div className="min-h-screen bg-[var(--sf-black)] text-white">
      <SfsContainer className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-4">
            <Link
              href="/dashboard"
              className="inline-flex items-center gap-2 text-[var(--sf-gold)] hover:text-[var(--sf-gold-2)] transition-colors text-sm"
            >
              <ArrowLeft className="w-4 h-4" />
              Dashboard
            </Link>
            <div className="w-12 h-12 bg-gradient-to-br from-[var(--sf-gold)] to-[var(--sf-gold-2)] rounded-xl flex items-center justify-center shadow-[var(--sf-glow-gold-sm)]">
              <Users className="w-6 h-6 text-[var(--sf-black)]" />
            </div>
            <div>
              <GoldHeading level={1} className="text-2xl font-bold">Client Management</GoldHeading>
              <p className="text-neutral-400 text-sm">Manage your e-commerce clients and their social media bots</p>
            </div>
          </div>
          <GoldButton
            onClick={() => setIsAddDialogOpen(true)}
            className="inline-flex items-center justify-center gap-2"
          >
            <Plus className="w-4 h-4" />
            Add Client
          </GoldButton>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {stats.map(({ label, value, Icon, sub }) => (
            <GlassCard key={label} className="p-5">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-medium text-neutral-400">{label}</span>
                <Icon className="h-4 w-4 text-[var(--sf-gold)]" />
              </div>
              <div className="text-2xl font-bold text-white">{value}</div>
              {sub && <p className="text-xs text-neutral-400 mt-1">{sub}</p>}
            </GlassCard>
          ))}
        </div>

        <GlassCard className="p-6">
          <div className="mb-4">
            <GoldHeading level={2} className="text-lg font-semibold">Your Clients</GoldHeading>
            <p className="text-neutral-400 text-sm mt-1">
              Manage your e-commerce clients and their social media bots
            </p>
          </div>

          {isLoading ? (
            <div className="text-center py-8 text-neutral-400">Loading clients...</div>
          ) : clients.length === 0 ? (
            <div className="text-center py-12">
              <Users className="mx-auto h-12 w-12 text-neutral-500 mb-4" />
              <GoldHeading level={3} className="text-lg font-medium mb-2">No clients yet</GoldHeading>
              <p className="text-neutral-400 mb-4">
                Add your first client to start managing their social media bots
              </p>
              <GoldButton
                onClick={() => setIsAddDialogOpen(true)}
                className="inline-flex items-center justify-center"
              >
                <Plus className="w-4 h-4 mr-2" />
                Add Your First Client
              </GoldButton>
            </div>
          ) : (
            <div className="space-y-4">
              {clients.map((client) => (
                <GlassCard
                  key={client.id}
                  className="flex items-center justify-between p-4 hover:!border-[var(--sf-gold)]/30 transition-colors"
                >
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-2">
                      <h3 className="text-lg font-semibold text-white">{client.businessName}</h3>
                      <Badge
                        className={
                          client.status === "active"
                            ? "bg-emerald-900/40 text-emerald-300 border border-emerald-500/30"
                            : "bg-neutral-800 text-neutral-300"
                        }
                      >
                        {client.status}
                      </Badge>
                    </div>
                    {client.contactEmail && (
                      <p className="text-sm text-neutral-400">{client.contactEmail}</p>
                    )}
                    <div className="flex items-center gap-6 mt-2 flex-wrap">
                      <div className="flex items-center gap-2">
                        <DollarSign className="w-4 h-4 text-[var(--sf-gold)]" />
                        <span className="text-sm text-white font-semibold">£{client.monthlyFee}/mo</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <Bot className="w-4 h-4 text-[var(--sf-gold)]" />
                        <span className="text-sm text-neutral-400">{client.botCount || 0} bots</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <TrendingUp className="w-4 h-4 text-[var(--sf-gold)]" />
                        <span className="text-sm text-neutral-400">
                          £{(client.totalRevenue || 0).toFixed(2)} revenue
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Link
                      href={`/clients/${client.id}`}
                      className="inline-flex items-center justify-center text-xs px-3 py-2 rounded-md border border-[var(--sf-gold)]/30 text-[var(--sf-gold)] hover:bg-[var(--sf-gold)]/10 hover:text-[var(--sf-gold-2)] transition-colors"
                    >
                      View Details
                    </Link>
                    <GhostButton
                      onClick={() => handleDeleteClient(client.id)}
                      className="text-xs px-3 !text-red-400 hover:!text-red-300"
                    >
                      <Trash2 className="w-4 h-4" />
                    </GhostButton>
                  </div>
                </GlassCard>
              ))}
            </div>
          )}
        </GlassCard>
      </SfsContainer>

      <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
        <DialogContent className="bg-[#0e0e0e] border border-[var(--sf-gold)]/20 text-white">
          <DialogHeader>
            <DialogTitle className="text-white">Add New Client</DialogTitle>
            <DialogDescription className="text-neutral-400">
              Add a new e-commerce business to manage their social media bots
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="businessName" className="text-white">Business Name *</Label>
              <Input
                id="businessName"
                placeholder="Joe's Sneakers"
                value={formData.businessName}
                onChange={(e) => setFormData({ ...formData, businessName: e.target.value })}
                className="bg-white/5 border-white/10 text-white"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="contactEmail" className="text-white">Contact Email</Label>
              <Input
                id="contactEmail"
                type="email"
                placeholder="joe@sneakers.com"
                value={formData.contactEmail}
                onChange={(e) => setFormData({ ...formData, contactEmail: e.target.value })}
                className="bg-white/5 border-white/10 text-white"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="contactPhone" className="text-white">Contact Phone</Label>
              <Input
                id="contactPhone"
                placeholder="+44 7700 900000"
                value={formData.contactPhone}
                onChange={(e) => setFormData({ ...formData, contactPhone: e.target.value })}
                className="bg-white/5 border-white/10 text-white"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="monthlyFee" className="text-white">Monthly Fee (£) *</Label>
              <Input
                id="monthlyFee"
                type="number"
                placeholder="200"
                value={formData.monthlyFee}
                onChange={(e) => setFormData({ ...formData, monthlyFee: e.target.value })}
                className="bg-white/5 border-white/10 text-white"
              />
            </div>
          </div>
          <DialogFooter>
            <GhostButton onClick={() => setIsAddDialogOpen(false)}>Cancel</GhostButton>
            <GoldButton
              onClick={handleAddClient}
              disabled={!formData.businessName || !formData.monthlyFee || createClientMutation.isPending}
              className="inline-flex items-center justify-center disabled:opacity-50"
            >
              {createClientMutation.isPending ? "Creating..." : "Create Client"}
            </GoldButton>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
